# Android-only adapters at the project boundary; never patch pinned dependencies.
if(NOT ANDROID)
    return()
endif()
if(NOT ANDROID_ABI STREQUAL "arm64-v8a")
    message(FATAL_ERROR "The Android qualification target currently requires arm64-v8a.")
endif()
if(CMAKE_ANDROID_NDK_VERSION VERSION_LESS "29")
    message(FATAL_ERROR "Android requires NDK r29 or newer for std::jthread/stop_token support.")
endif()
if(ANDROID_PLATFORM_LEVEL LESS 28)
    message(FATAL_ERROR "Android requires API 28 or newer for the isolated importer process.")
endif()
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(DKR_RUNTIME_BUILD_SDL3_INPUT_HOST OFF CACHE BOOL "Android uses in-process SDL2 input" FORCE)
set(DKR_ANDROID_SDL2_SOURCE "" CACHE PATH "Unmodified SDL2 2.32.10 source")
set(DKR_HOST_FILE_TO_C "" CACHE FILEPATH "Native host RT64 file_to_c executable")
if(NOT EXISTS "${DKR_ANDROID_SDL2_SOURCE}/CMakeLists.txt" OR NOT EXISTS "${DKR_HOST_FILE_TO_C}")
    message(FATAL_ERROR "Android requires DKR_ANDROID_SDL2_SOURCE and DKR_HOST_FILE_TO_C.")
endif()
set(SDL_SHARED ON CACHE BOOL "Android SDL library" FORCE)
set(SDL_STATIC OFF CACHE BOOL "No duplicate SDL runtime" FORCE)
set(SDL_TEST OFF CACHE BOOL "No SDL tests in APK" FORCE)
# The runtime reads/compresses existing dictionaries; it never trains them.
# The pinned trainer uses glibc qsort_r, unavailable on Android API 28.
set(ZSTD_BUILD_DICTBUILDER OFF CACHE BOOL "No offline dictionary training on Android" FORCE)
set(ZSTD_BUILD_PROGRAMS OFF CACHE BOOL "No desktop compression tools in APK" FORCE)
set(ZSTD_BUILD_TESTS OFF CACHE BOOL "No desktop compression tests in APK" FORCE)
add_subdirectory("${DKR_ANDROID_SDL2_SOURCE}" "${CMAKE_BINARY_DIR}/sdl2" EXCLUDE_FROM_ALL)
include("${CMAKE_CURRENT_LIST_DIR}/android/SdlPatches.cmake")
list(PREPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/android")
set(CMAKE_PROJECT_nativefiledialog-extended_INCLUDE
    "${CMAKE_CURRENT_LIST_DIR}/android/NfdPlatform.cmake")
set(CMAKE_PROJECT_plume_INCLUDE "${CMAKE_CURRENT_LIST_DIR}/android/HostShaders.cmake")
add_link_options("-Wl,-z,max-page-size=16384")
