# Android presentation patch pipeline. Patch only isolated build-stage copies;
# never mutate the dependency checkout or the generated guest CPU payloads.
if(NOT ANDROID)
    return()
endif()
find_package(Git REQUIRED)
set(_dkr_renderer_stage "${CMAKE_BINARY_DIR}/generated/android-renderer")
set(_dkr_renderer_patch "${DKRPORT_ROOT}/patches/android/rt64-rgba-presentation.patch")
set(_dkr_renderer_files src/hle/rt64_application.cpp src/render/rt64_shader_library.cpp)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_dkr_renderer_patch}")
foreach(_file IN LISTS _dkr_renderer_files)
    get_filename_component(_parent "${_file}" DIRECTORY)
    file(MAKE_DIRECTORY "${_dkr_renderer_stage}/${_parent}")
    configure_file("${DKR_RT64_SOURCE}/${_file}" "${_dkr_renderer_stage}/${_file}" COPYONLY)
endforeach()
# A private, untracked build-stage repository makes git apply independent of
# whether the build directory is inside or outside the project's worktree.
execute_process(COMMAND "${GIT_EXECUTABLE}" init --quiet "${_dkr_renderer_stage}"
    RESULT_VARIABLE _result ERROR_VARIABLE _error)
if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Cannot prepare Android renderer patch stage: ${_error}")
endif()
foreach(_mode IN ITEMS check apply)
    set(_flags)
    if(_mode STREQUAL "check")
        set(_flags --check)
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${_dkr_renderer_stage}"
        apply ${_flags} --whitespace=error "${_dkr_renderer_patch}"
        RESULT_VARIABLE _result ERROR_VARIABLE _error)
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR "Android renderer patch ${_mode} failed; dependency context changed: ${_error}")
    endif()
endforeach()
get_target_property(_sources rt64 SOURCES)
foreach(_file IN LISTS _dkr_renderer_files)
    get_filename_component(_name "${_file}" NAME)
    set(_matches ${_sources})
    list(FILTER _matches INCLUDE REGEX "(^|/)${_name}$")
    list(LENGTH _matches _count)
    if(NOT _count EQUAL 1)
        message(FATAL_ERROR "Expected exactly one RT64 source for ${_file}, found ${_count}")
    endif()
    list(REMOVE_ITEM _sources ${_matches})
    list(APPEND _sources "${_dkr_renderer_stage}/${_file}")
    get_filename_component(_parent "${_file}" DIRECTORY)
    set_source_files_properties("${_dkr_renderer_stage}/${_file}" TARGET_DIRECTORY rt64
        PROPERTIES INCLUDE_DIRECTORIES "${DKR_RT64_SOURCE}/${_parent}")
endforeach()
set_property(TARGET rt64 PROPERTY SOURCES "${_sources}")
