#include "netplay/experimental_pcm.hpp"
#include <array>
#include <cassert>
#include <cstring>
#include <iostream>
using dkr::runtime::netplay::experimental::pcm_s16le_from_guest;
int main() {
    // Independent N64 word-swapped representation, not generated by the
    // routine being tested: L=0x1234, R=-10000 (0xD8F0), then extrema.
    const std::array<std::uint8_t,12> guest{0xF0,0xD8,0x34,0x12,0xFF,0x7F,0x00,0x80,0,0,0,0};
    const std::array<std::uint8_t,8> expected{0x34,0x12,0xF0,0xD8,0x00,0x80,0xFF,0x7F};
    std::array<std::uint8_t,8> output{};
    assert(pcm_s16le_from_guest(guest,0,output) && output==expected);
    const auto unchanged=output;
    assert(!pcm_s16le_from_guest(guest,1,output) && output==unchanged);
    assert(!pcm_s16le_from_guest(guest,8,output) && output==unchanged);
    assert(!pcm_s16le_from_guest(guest,0,std::span(output).first(7)) && output==unchanged);
    // Compare every 16-bit bit pattern against the normal runtime's native
    // int16 stereo-pair swap, independently of the experimental byte helper.
    // Also exercise a nonzero RAM offset, with sentinels outside that frame.
    for(unsigned bits=0;bits<65536;++bits) {
        const std::uint16_t left=std::uint16_t(bits),right=std::uint16_t(bits^0x5AA5U);
        std::array<std::uint8_t,12> ram{};ram.fill(0xCC);
        std::memcpy(ram.data()+4,&right,2);std::memcpy(ram.data()+6,&left,2);
        std::array<std::int16_t,2> normal_native{};
        std::memcpy(normal_native.data(),ram.data()+4,4);
        const std::array<std::int16_t,2> normal_output{normal_native[1],normal_native[0]};
        std::array<std::uint8_t,4> normal_bytes{},experimental_bytes{};
        std::memcpy(normal_bytes.data(),normal_output.data(),4);
        assert(pcm_s16le_from_guest(ram,4,experimental_bytes));
        assert(experimental_bytes==normal_bytes);
        assert(ram[3]==0xCC && ram[8]==0xCC);
    }
    std::cout<<"Experimental PCM: independently encoded stereo/range tests and all 65536 sample patterns match normal native audio conversion\n";
}
